blank_issues_enabled: false
contact_links:
  - name: Marketing Support
    url: https://jira.linuxfoundation.org/plugins/servlet/desk/portal/23/create/511
    about: Submit a guest blog post for aswf.io and/or linux.com, video to upload to YouTube, host a webinar, or any other social media request.
  - name: Project Infrastructure Support
    url: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/group/6
    about: Request new or changes to mailing list, Slack channel, GitHub organization, 1Password vault, or other infrastructure
  - name: Transfer domain to Academy Software Foundation
    url: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63
    about: For transfering a project-owned domain to the LF Energy
  - name: Academy Software Foundation Landscape entry requests
    url: https://github.com/AcademySoftwareFoundation/aswf-landscape/issues/new/choose
    about: Any requests for adding or updating Academy Software Foundation Landscape entries
  - name: Other Academy Software Foundation member support requests
    url: http://members.openmainframeproject.org/
    about: Member specific requests, including invoicing, contact management, and participation in member-exclusive groups
